substitutions:
  friendly_name: "Device Entity"
  project_name: "3ative.project-name"
  project_version: "1.0"
  
esphome:
  name: "project-name"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"
    
esp8266:
  board: d1_mini

logger:
api:
ota:

mdns:
  disabled: false

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://3ative/projects/project-name.yaml

switch:
  - platform: gpio
    name: "${friendly_name} switch"
    pin: GPIO12
    id: relay
    restore_mode: ${relay_restore_mode}
 
light:
  - platform: binary
    name: "${friendly_name} Blue LED"
    id: blue_led
    output: light_output

output:
  - id: light_output
    platform: gpio
    pin: GPIO3
